site_name: Firestorm

pages:
- Introduction:
    - Home: 'index.md'
    - What is Firestorm?: 'intro/what-is-firestorm.md'
    - Aims: 'intro/aims.md'
    
- Installation and Setup:
    - Installation: 'setup/installation.md'
    - Configuration Object: 'setup/configuration-builder.md'
    - Chosing a Methodology: 'setup/chosing-a-methodology.md'

- Endpoints:
    - Navigation: 'endpoints/navigation.md'
    - Querying: 'endpoints/querying.md'
    - Pagination: 'endpoints/pagination.md'
    - Write Operations: 'endpoints/write-operations.md'
    - Errors: 'endpoints/errors.md'
    - Configuration: 'endpoints/endpoint-config.md'
    
- Stems: 
    - Introduction: 'stems/stems-intro.md'
    - Setup: 'stems/stems-setup.md'
    - Basics: 'stems/stems-basics.md'
    - Other Expressions: 'stems/other-expressions.md'
    - Identifiers: 'stems/identifiers.md'
    - Substems: 'stems/substems.md'
    - Nesting: 'stems/nesting.md'
    - Dependency Injection: 'stems/dependency-injection.md'
    - Modification: 'stems/modification.md'
    - Authorisation: 'stems/authorisation.md'
    - Best Practices: 'stems/best-practices.md'
    - Roots: 'stems/roots.md'
    
- Fluent: 
    - Introduction: 'fluent/fluent-intro.md'
    - Setup: 'fluent/fluent-setup.md'
    - Builder API: 'fluent/builder-api.md'

- Contributors:
    - Solution Architecture: 'contrib/solution-architecture.md'
    - Packages: 'contrib/packages.md'
    - Future Development: 'contrib/future-developments.md'
    
theme: readthedocs

markdown_extensions:
  - admonition